// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using Where2Play.Models;
//
//    var welcome = Welcome.FromJson(jsonString);

namespace Where2Play.Models
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class Welcome
    {
        [JsonProperty("type")]
        public string Type { get; set; }

        [JsonProperty("itemsPerPage")]
        public long ItemsPerPage { get; set; }

        [JsonProperty("page")]
        public long Page { get; set; }

        [JsonProperty("total")]
        public long Total { get; set; }

        [JsonProperty("setlist")]
        public Setlist[] Setlist { get; set; }
    }

    public partial class Setlist
    {
        [JsonProperty("id")]
        public string Id { get; set; }

        [JsonProperty("versionId")]
        public string VersionId { get; set; }

        [JsonProperty("eventDate")]
        public string EventDate { get; set; }

        [JsonProperty("lastUpdated")]
        public string LastUpdated { get; set; }

        [JsonProperty("artist")]
        public Artist Artist { get; set; }

        [JsonProperty("venue")]
        public Venue Venue { get; set; }

        [JsonProperty("sets")]
        public Sets Sets { get; set; }

        [JsonProperty("url")]
        public Uri Url { get; set; }

        [JsonProperty("info", NullValueHandling = NullValueHandling.Ignore)]
        public string Info { get; set; }
    }

    public partial class Artist
    {
        [JsonProperty("mbid")]
        public Guid Mbid { get; set; }

        [JsonProperty("name")]
        public string ConcertsArtistName { get; set; }

        [JsonProperty("sortName")]
        public string ConcertsSortName { get; set; }

        [JsonProperty("disambiguation")]
        public Disambiguation Disambiguation { get; set; }

        [JsonProperty("url")]
        public Uri Url { get; set; }
    }

    public partial class Sets
    {
        [JsonProperty("set")]
        public Set[] Set { get; set; }
    }

    public partial class Set
    {
        [JsonProperty("song")]
        public Song[] Song { get; set; }

        [JsonProperty("encore", NullValueHandling = NullValueHandling.Ignore)]
        public long? Encore { get; set; }

        [JsonProperty("name", NullValueHandling = NullValueHandling.Ignore)]
        public string Name { get; set; }
    }

    public partial class Song
    {
        [JsonProperty("name")]
        public string Name { get; set; }

        [JsonProperty("cover", NullValueHandling = NullValueHandling.Ignore)]
        public Artist Cover { get; set; }

        [JsonProperty("with", NullValueHandling = NullValueHandling.Ignore)]
        public Artist With { get; set; }

        [JsonProperty("tape", NullValueHandling = NullValueHandling.Ignore)]
        public bool? Tape { get; set; }

        [JsonProperty("info", NullValueHandling = NullValueHandling.Ignore)]
        public string Info { get; set; }
    }

    public partial class Venue
    {
        [JsonProperty("id")]
        public string Id { get; set; }

        [JsonProperty("name")]
        public string Name { get; set; }

        [JsonProperty("city")]
        public City City { get; set; }

        [JsonProperty("url")]
        public Uri Url { get; set; }
    }

    public partial class City
    {
        [JsonProperty("id")]
        [JsonConverter(typeof(ParseStringConverter))]
        public long Id { get; set; }

        [JsonProperty("name")]
        public string Name { get; set; }

        [JsonProperty("state")]
        public string State { get; set; }

        [JsonProperty("stateCode")]
        public string StateCode { get; set; }

        [JsonProperty("coords")]
        public Coords Coords { get; set; }

        [JsonProperty("country")]
        public Country Country { get; set; }
    }

    public partial class Coords
    {
        [JsonProperty("lat")]
        public double Lat { get; set; }

        [JsonProperty("long")]
        public double Long { get; set; }
    }

    public partial class Country
    {
        [JsonProperty("code")]
        public string Code { get; set; }

        [JsonProperty("name")]
        public string Name { get; set; }
    }

    public enum Disambiguation { AmericanSingerSongwriterAndPianist, Empty, GermanBaroquePeriodComposerMusician, LAIndieSingerSongwriterFkaEvaBRoss, SoulSinger, TheBeatles, UsSoulSingerSongwriterPastorAndRecordProducer };


    internal class DisambiguationConverter : JsonConverter
    {
        public override bool CanConvert(Type t) => t == typeof(Disambiguation) || t == typeof(Disambiguation?);

        public override object ReadJson(JsonReader reader, Type t, object existingValue, JsonSerializer serializer)
        {
            if (reader.TokenType == JsonToken.Null) return null;
            var value = serializer.Deserialize<string>(reader);
            switch (value)
            {
                case "":
                    return Disambiguation.Empty;
                case "American singer-songwriter and pianist":
                    return Disambiguation.AmericanSingerSongwriterAndPianist;
                case "German Baroque period composer & musician":
                    return Disambiguation.GermanBaroquePeriodComposerMusician;
                case "L.A. indie singer-songwriter, fka Eva B. Ross":
                    return Disambiguation.LAIndieSingerSongwriterFkaEvaBRoss;
                case "The Beatles":
                    return Disambiguation.TheBeatles;
                case "US soul singer, songwriter, pastor and record producer":
                    return Disambiguation.UsSoulSingerSongwriterPastorAndRecordProducer;
                case "soul singer":
                    return Disambiguation.SoulSinger;
            }
            throw new Exception("Cannot unmarshal type Disambiguation");
        }

        public override void WriteJson(JsonWriter writer, object untypedValue, JsonSerializer serializer)
        {
            if (untypedValue == null)
            {
                serializer.Serialize(writer, null);
                return;
            }
            var value = (Disambiguation)untypedValue;
            switch (value)
            {
                case Disambiguation.Empty:
                    serializer.Serialize(writer, "");
                    return;
                case Disambiguation.AmericanSingerSongwriterAndPianist:
                    serializer.Serialize(writer, "American singer-songwriter and pianist");
                    return;
                case Disambiguation.GermanBaroquePeriodComposerMusician:
                    serializer.Serialize(writer, "German Baroque period composer & musician");
                    return;
                case Disambiguation.LAIndieSingerSongwriterFkaEvaBRoss:
                    serializer.Serialize(writer, "L.A. indie singer-songwriter, fka Eva B. Ross");
                    return;
                case Disambiguation.TheBeatles:
                    serializer.Serialize(writer, "The Beatles");
                    return;
                case Disambiguation.UsSoulSingerSongwriterPastorAndRecordProducer:
                    serializer.Serialize(writer, "US soul singer, songwriter, pastor and record producer");
                    return;
                case Disambiguation.SoulSinger:
                    serializer.Serialize(writer, "soul singer");
                    return;
            }
            throw new Exception("Cannot marshal type Disambiguation");
        }

        public static readonly DisambiguationConverter Singleton = new DisambiguationConverter();
    }
}