// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using Where2Play.Models;
//
//    var welcome = Welcome.FromJson(jsonString);

using Newtonsoft.Json;

namespace Where2Play.Models
{
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;
    using System;
    using System.Collections.Generic;
    using System.Globalization;

    public partial class MusicBrainzArtist
    {
        [JsonProperty("gender-id")]
        public object GenderId { get; set; }

        [JsonProperty("name")]
        public string Name { get; set; }

        [JsonProperty("begin-area")]
        public Area BeginArea { get; set; }

        [JsonProperty("ipis")]
        public object[] Ipis { get; set; }

        [JsonProperty("type")]
        public string Type { get; set; }

        [JsonProperty("life-span")]
        public LifeSpan LifeSpan { get; set; }

        [JsonProperty("area")]
        public Area Area { get; set; }

        [JsonProperty("sort-name")]
        public string SortName { get; set; }

        [JsonProperty("end-area")]
        public object EndArea { get; set; }

        [JsonProperty("country")]
        public string Country { get; set; }

        [JsonProperty("gender")]
        public object Gender { get; set; }

        [JsonProperty("isnis")]
        public string[] Isnis { get; set; }

        [JsonProperty("id")]
        public Guid Id { get; set; }

        [JsonProperty("type-id")]
        public Guid? TypeId { get; set; }

        [JsonProperty("disambiguation")]
        public string Disambiguation { get; set; }

        [JsonProperty("rating")]
        public Rating Rating { get; set; }

        [JsonProperty("genres")]
        public List<Genre> Genres { get; set; }
    }

    public partial class Area
    {
        [JsonProperty("id")]
        public Guid Id { get; set; }

        [JsonProperty("type-id")]
        public object? TypeId { get; set; }

        [JsonProperty("disambiguation")]
        public string Disambiguation { get; set; }

        [JsonProperty("sort-name")]
        public string SortName { get; set; }

        [JsonProperty("type")]
        public object Type { get; set; }

        [JsonProperty("name")]
        public string Name { get; set; }
    }

    public partial class LifeSpan
    {
        [JsonProperty("ended")]
        public bool Ended { get; set; }

        [JsonProperty("begin")]
        [JsonConverter(typeof(ParseStringConverter))]
        public object Begin { get; set; }

        [JsonProperty("end")]
        public object End { get; set; }
    }

    public partial class Rating
    {
        [JsonProperty("votes-count")]
        public long VotesCount { get; set; }

        [JsonProperty("value")]
        public double? Value { get; set; }
    }
    public partial class MusicBrainzArtist
    {
        public static MusicBrainzArtist FromJson(string json) => JsonConvert.DeserializeObject<MusicBrainzArtist>(json, Where2Play.Models.Converter.Settings);
    }
}

public partial class Genre
{
    [JsonProperty("id")]
    public Guid Id { get; set; }

    [JsonProperty("name")]
    public string Name { get; set; }

    [JsonProperty("count")]
    public long Count { get; set; }

    [JsonProperty("disambiguation")]
    public string Disambiguation { get; set; }
}